### ISSUE TITLE
Master TODO

### ISSUE THREAD

**Issue by m2n037** [m2n037/awesome-mecheng#7]
This serves as the master list of TODO

- [x] Add all ROS books from packt-pub
- [ ] Add all youtube playlists
- [ ] LS Dyna tutorial sites
- [ ] Ansys cornell sites
- [ ] FEM software books from my repo list
- [ ] Stackexchange recommended books for C++/Python
- [ ] Awesome lists from github to relvant sections
- [ ] EdX courses to relvant sections
- [ ] Add stuff to this list when you remember
- [ ] Create rules and regulations
- [ ] Cool answers from Quora
- [ ] Mechanism design books by DS
- [x] Jog free book for FEM
- [ ] Vector and Tensor book
- [ ] add robotics forum/abaqus nabble forum 
- [ ] altair university books
- [ ] Unix matt might page from my site
- [ ] nuts and bolts post
